# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: crytofy.user::lang.user.label

# Model Form Field configuration
form: $/crytofy/user/models/user/fields.yaml

# Model Class name
modelClass: Crytofy\User\Models\User

# Default redirect location
defaultRedirect: crytofy/user/users

# Create page
create:
    redirect: crytofy/user/users/preview/:id
    redirectClose: crytofy/user/users

# Update page
update:
    redirect: crytofy/user/users/update/:id
    redirectClose: crytofy/user/users/preview/:id
