# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: crytofy.user::lang.group.label

# Model Form Field configuration
form: $/crytofy/user/models/usergroup/fields.yaml

# Model Class name
modelClass: Crytofy\User\Models\UserGroup

# Default redirect location
defaultRedirect: crytofy/user/usergroups

# Create page
create:
    title: crytofy.user::lang.groups.create_title
    redirect: crytofy/user/usergroups/update/:id
    redirectClose: crytofy/user/usergroups

# Update page
update:
    title: crytofy.user::lang.groups.update_title
    redirect: crytofy/user/usergroups
    redirectClose: crytofy/user/usergroups

# Preview page
preview:
    title: crytofy.user::lang.groups.update_title